package artistle.emvfusion.entity

import artistle.emvfusion.utils.hex.toHexString

val emvTagNames = mapOf(
    "4F" to "Application Identifier (AID)",
    "50" to "Application Label",
    "57" to "Track 2 Equivalent Data",
    "5A" to "Application Primary Account Number (PAN)",
    "5F20" to "Cardholder Name",
    "5F24" to "Application Expiration Date",
    "5F25" to "Application Effective Date",
    "5F28" to "Issuer Country Code",
    "5F2A" to "Transaction Currency Code",
    "5F2D" to "Language Preference",
    "5F30" to "Service Code",
    "5F34" to "Application Primary Account Number (PAN) Sequence Number",
    "5F36" to "Transaction Currency Exponent",
    "5F50" to "Issuer URL",
    "5F55" to "Issuer Country Code (alpha3)",
    "5F57" to "Account Type",
    "61" to "Application Template",
    "6F" to "File Control Information (FCI) Template",
    "70" to "Record Template",
    "71" to "Issuer Script Template 1",
    "72" to "Issuer Script Template 2",
    "73" to "Directory Discretionary Template",
    "77" to "Response Message Template Format 2",
    "80" to "Response Message Template Format 1",
    "82" to "Application Interchange Profile (AIP)",
    "84" to "Dedicated File (DF) Name (AID)",
    "86" to "Issuer Script Command",
    "87" to "Application Priority Indicator",
    "88" to "Short File Identifier (SFI)",
    "8C" to "Card Risk Management Data Object List 1 (CDOL1)",
    "8D" to "Card Risk Management Data Object List 2 (CDOL2)",
    "8E" to "Cardholder Verification Method (CVM) List",
    "8F" to "Certification Authority Public Key Index",
    "90" to "Issuer Public Key Certificate",
    "91" to "Issuer Authentication Data",
    "92" to "Issuer Public Key Remainder",
    "93" to "Signed Static Application Data",
    "94" to "Application File Locator (AFL)",
    "95" to "Terminal Verification Results (TVR)",
    "97" to "Transaction Certificate Data Object List (TDOL)",
    "98" to "Transaction Certificate (TC) Hash Value",
    "99" to "Transaction Personal Identification Number (PIN) Data",
    "9A" to "Transaction Date",
    "9B" to "Transaction Status Information",
    "9C" to "Transaction Type",
    "9D" to "Directory Definition File (DDF) Name",
    "9F01" to "Acquirer Identifier",
    "9F02" to "Amount, Authorised (Transaction)",
    "9F03" to "Amount, Other (Cardholder Billing)",
    "9F04" to "Amount, Other (Issuer)",
    "9F05" to "Application Discretionary Data",
    "9F06" to "Application Identifier (AID) – terminal",
    "9F07" to "Application Usage Control",
    "9F08" to "Application Version Number",
    "9F09" to "Application Version Number (terminal)",
    "9F0B" to "Cardholder Name Extended",
    "9F0D" to "Issuer Action Code - Default",
    "9F0E" to "Issuer Action Code - Denial",
    "9F0F" to "Issuer Action Code - Online",
    "9F10" to "Issuer Application Data (IAD)",
    "9F11" to "Issuer Code Table Index",
    "9F12" to "Application Preferred Name",
    "9F13" to "Last Online Application Transaction Counter (ATC) Register",
    "9F14" to "Lower Consecutive Offline Limit",
    "9F15" to "Merchant Category Code",
    "9F16" to "Merchant Identifier",
    "9F17" to "Personal Identification Number (PIN) Try Counter",
    "9F18" to "Issuer Script Identifier",
    "9F1A" to "Terminal Country Code",
    "9F1B" to "Terminal Floor Limit",
    "9F1C" to "Terminal Identification",
    "9F1D" to "Terminal Risk Management Data",
    "9F1E" to "Interface Device (IFD) Serial Number",
    "9F1F" to "Track 1 Discretionary Data",
    "9F20" to "Track 2 Discretionary Data",
    "9F21" to "Transaction Time",
    "9F22" to "Certification Authority Public Key Index (terminal)",
    "9F23" to "Upper Consecutive Offline Limit",
    "9F26" to "Application Cryptogram",
    "9F27" to "Cryptogram Information Data",
    "9F2D" to "ICC PIN Encipherment Public Key Certificate",
    "9F2E" to "ICC PIN Encipherment Public Key Exponent",
    "9F2F" to "ICC PIN Encipherment Public Key Remainder",
    "9F32" to "Issuer Public Key Exponent",
    "9F33" to "Terminal Capabilities",
    "9F34" to "Cardholder Verification Method (CVM) Results",
    "9F35" to "Terminal Type",
    "9F36" to "Application Transaction Counter (ATC)",
    "9F37" to "Unpredictable Number",
    "9F38" to "Processing Options Data Object List (PDOL)",
    "9F39" to "Point-of-Service Entry Mode",
    "9F3A" to "Amount, Reference Currency",
    "9F3B" to "Application Reference Currency",
    "9F3C" to "Transaction Reference Currency Code",
    "9F3D" to "Transaction Reference Currency Exponent",
    "9F40" to "Additional Terminal Capabilities",
    "9F41" to "Transaction Sequence Counter",
    "9F42" to "Application Currency Code",
    "9F43" to "Application Reference Currency Exponent",
    "9F44" to "Application Currency Exponent",
    "9F45" to "Data Authentication Code",
    "9F46" to "ICC Public Key Certificate",
    "9F47" to "ICC Public Key Exponent",
    "9F48" to "ICC Public Key Remainder",
    "9F49" to "Dynamic Data Authentication Data Object List (DDOL)",
    "9F4A" to "Static Data Authentication Tag List",
    "9F4B" to "Signed Dynamic Application Data",
    "9F4C" to "ICC Dynamic Number",
    "9F4D" to "Log Entry",
    "9F4E" to "Merchant Name and Location",
    "9F4F" to "Log Format",
    "9F5D" to "Available Offline Spending Amount",
    "9F5E" to "DS ODS Term Risk Management Data",
    "9F5F" to "DS Input Term BDK Identifier",
    "9F60" to "CVC3 Track1",
    "9F61" to "CVC3 Track2",
    "9F62" to "Track1 Bit Map for CVC3",
    "9F63" to "Track2 Bit Map for CVC3",
    "9F64" to "Application Transaction Counter (ATC) Last Online ATC Register",
    "9F65" to "Application Transaction Counter (ATC) History",
    "9F66" to "Terminal Transaction Qualifiers (TTQ)",
    "9F67" to "Mag Stripe Application Version Number",
    "9F68" to "Card Additional Processes",
    "9F69" to "Application Restrictions",
    "9F6B" to "Track 2 Data",
    "9F6C" to "Mag Stripe CVM List",
    "9F6E" to "Third Party Data",
    "9F7A" to "Unpredictable Number Data Object List (UN DOL)",
    "9F7B" to "Online PIN Required Terminal",
    "9F7C" to "Merchant Custom Data",
    "BF0C" to "FCI Issuer Discretionary Data",
    "DF01" to "MIR - Proprietary AID Info",
    "DF02" to "MIR - Terminal Type",
    "DFEE12" to "Proprietary Merchant Identifier"
)


fun describeTag(tag: ByteArray): String {
    return emvTagNames[tag.toHexString()] ?: "Unknown Tag"
}

fun describeTag(tag: String): String {
    return emvTagNames[tag] ?: "Unknown Tag"
}